title: "Titre de ton blog/article"
description: "Description de ton contenu"
baseurl: "/nom-de-ton-repo"
url: "https://ton-username.github.io"

# Utilise remote_theme au lieu de theme
remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-include-cache  # nécessaire pour minimal-mistakes